name:                hhwloc
version:             0.2.0
github:              "dtaskoff/hhwloc"
license:             MIT
author:              "Daniel Taskoff"
maintainer:          "daniel.taskoff@gmail.com"
copyright:           "2020 (c) Daniel Taskoff"

synopsis:            Bindings to https://www.open-mpi.org/projects/hwloc
category:            Foreign, System

description:         Please see the README on GitHub at <https://github.com/dtaskoff/hhwloc#readme>

extra-doc-files:
- README.md
- CHANGELOG.md

extra-source-files:
- hwloc/autogen.sh
- hwloc/configure.ac
- hwloc/VERSION
- hwloc/**/Makefile.am
- hwloc/**/*.in
- hwloc/config/*.m4
- hwloc/config/*.sh
- hwloc/hwloc/*.c
- hwloc/hwloc/hwloc*.dtd
- hwloc/include/hwloc.h
- hwloc/include/hwloc/autogen/config.h.in
- hwloc/include/hwloc/*.h
- hwloc/include/private/*.h
- hwloc/utils/lstopo/lstopo-windows.c

data-files:
- hwloc/COPYING
- hwloc/include/private/autogen/README.txt

custom-setup:
  dependencies:
  - base
  - Cabal
  - directory

dependencies:
- base >= 4.7 && < 5

default-extensions:
- BlockArguments
- LambdaCase

library:
  source-dirs: src
  include-dirs: hwloc/include

ghc-options:
- -Wall
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates
